### PR TITLE
Update inputs and copy on tell us about yourself page

### PR DESCRIPTION
**Pull request by joshstroud-cfa**

### CODE REVIEW

**Comment by joshstroud-cfa** [comment]
@tdooner I left the hooks, submission properties, and language properties in the file so we can have them as a reference. They seemed easy to remove. Let me know if/when we should remove them!

**Comment by tdooner** [comment]
I'm generally not a fan of keeping dead code around (since I tend to forget and then it sticks around way longer than I intend), so I'd suggest removing.

**Comment by joshstroud-cfa** [comment]
Sure, I'll take out the dead code before I merge.

**Comment by joshstroud-cfa** [comment]
Also flagging for myself on this one that tests failed and need to update the journey test with the new behavior.

**Pull request merged**
